name: Lorrytron
favicon: null
layout_spectrum: 0.98103
typography_spectrum: 0.32845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d2cf'
    - '#e9853c'
    - '#080506'
    - '#126737'
    - '#9a402a'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
