name: Lawrence Fung
favicon: null
layout_spectrum: 0
typography_spectrum: 0.78096
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Lawrey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#916F64'
    - '#312621'
    - '#EAE8E8'
    - '#204C77'
    - '#D04043'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
